### ISSUE TITLE
Monitoring activity inside docker container

### ISSUE THREAD

**Issue by pe1mew** [ThingsIXFoundation/packet-handling#25]
Is there a way to monitor activity of a forwarder in a docker container and get similar information to when using the container in the foreground? for example monitoring the logging?

**Comment by timcooijmans** [comment]
If you are using a docker-container you can use the build-in `docker logs` command. For example: `docker logs forwarder`. This command also has "follow" support with `-f`

**Comment by pe1mew** [comment]
Thanks for pointing at it. The following command is best for me: 
```
 docker logs thingsix-forwarder -n 10 -f
```
